# require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
# require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

# platform :ios, '12.0'

# require 'json'
# podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

# target 'HappiMynd' do
#   use_expo_modules!
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
#   )

#   permissions_path = '../node_modules/react-native-permissions/ios'

#   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
#   pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

#   pod 'RNIap', :path => '../node_modules/react-native-iap'
#   pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'
#   # Uncomment to opt-in to using Flipper
#   #
#   # if !ENV['CI']
#   #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
#   # end

#   pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

#   pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

#   pod 'react-native-network-info', :path => '../node_modules/react-native-network-info'

#   # pod 'RNAudiotransition', :path => '../node_modules/react-native-audiotransition'

#   pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

#   post_install do |installer|
#     react_native_post_install(installer)

#     # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
#     # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
#     installer.pods_project.targets.each do |target|
#       if (target.name&.eql?('FBReactNativeSpec'))
#         target.build_phases.each do |build_phase|
#           config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#           # Set the minimum iOS deployment target to 15.0
#           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
          
#           if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
#             target.build_phases.move(build_phase, 0)
#           end
#         end
#       end
#     end
#   end

# end


require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '13.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

# Set Firebase SDK version for expo-firebase-analytics
$FirebaseSDKVersion = '9.5.0'

target 'HappiMynd' do
  use_expo_modules!
  config = use_native_modules!
  
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  )

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

  pod 'RNIap', :path => '../node_modules/react-native-iap'
  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'
  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  # end

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-network-info', :path => '../node_modules/react-native-network-info'

  # pod 'RNAudiotransition', :path => '../node_modules/react-native-audiotransition'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  # Use updated glog that compiles with Xcode 26+ SDK
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  post_install do |installer|
    react_native_post_install(installer)

    # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
    # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Set minimum iOS deployment target to 13.0 for Xcode 26.4 compatibility
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        # Disable bitcode for all pods
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
        # Disable deprecated literal operator warning for Yoga compatibility with Xcode 26.4
        if target.name == 'Yoga'
          config.build_settings['GCC_WARN_PEDANTIC'] = 'NO'
          config.build_settings['CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'NO'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
      end
      
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          config = installer.pods_project.build_configuration_list
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end

      # Fix shell scripts that use `bash -l -c` with paths containing spaces.
      # The outer shell expands $VAR references, then inner bash splits on spaces.
      target.build_phases.each do |build_phase|
        if build_phase.respond_to?(:shell_script) && build_phase.shell_script
          script = build_phase.shell_script

          # Fix FBReactNativeSpec: VAR=/path/with space/... -> VAR="/path/with space/..."
          if script.include?("bash -l -c '")
            parts = script.split("'")
            if parts.length >= 3
              cmd = parts[1]
              cmd = cmd.gsub(/(\w+)=(\S+ \S+?)(?=\s+\w+=)/) { "#{$1}=\"#{$2}\"" }
              cmd = cmd.gsub(/(\S+ \S+\/generate-specs\.sh)/) { "\"#{$1}\"" }
              parts[1] = cmd
              script = parts.join("'")
            end
          end

          # Fix EXConstants-style: bash -l -c "$VAR/path" -> bash -l -c "\"$VAR/path\""
          script = script.gsub(/bash -l -c "\$(\w+)([^"]*)"/) {
            'bash -l -c "\"$' + $1 + $2 + '\""'
          }

          build_phase.shell_script = script
        end
      end
    end
  end

end
